"""posts table

Revision ID: 645c7aff41e6
Revises: 6e860a9b800c
Create Date: 2020-07-08 22:05:17.781814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645c7aff41e6'
down_revision = '6e860a9b800c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    # ### end Alembic commands ###
